#!/usr/bin/env bash
set -euf -o pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <size_mb>"
  exit 1
fi

MB="$1"
shift
adb shell mkdir -p /sdcard/WhatsApp/Databases
adb shell dd if=/dev/zero of="/sdcard/WhatsApp/Databases/msgstore-$RANDOM-$RANDOM-$RANDOM.1.db.crypt12" bs=1m count="$MB"
