# This is a basic workflow to help you get started with Actions

name: release
on: push
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Setup environment
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
      
    - name: Setup the Android SDK part that sucks
      run: mise run setup-androidsdk

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
      id: extract_branch
      
    - run: mise run install:flutter
    - run: mise run codegen:icons
#    - run: flutter test
    - run: mise run build:apk
    - run: mise run build:aab
      
    - name: Create a Release APK
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1
      with:
        artifacts: "build/app/outputs/bundle/release/app-release.aab,build/app/outputs/flutter-apk/app-release.apk"
        name: Compilação automática ${{ github.sha }} para branch ${{ steps.extract_branch.outputs.branch }}
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ steps.extract_branch.outputs.branch }}
        tag: commit-${{ github.sha }}
        draft: true
        prerelease: true
